# Generated by Django 5.2.2 on 2025-07-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ville',
            field=models.CharField(default='Bandjoun', help_text="Ville de résidence de l'utilisateur", max_length=100, verbose_name='ville de résidence'),
        ),
    ]
