# Generated by Django 5.2.2 on 2025-07-05 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='departure_time',
            field=models.TimeField(blank=True, help_text='Time when the tour departs', null=True, verbose_name='Departure Time'),
        ),
        migrations.AddField(
            model_name='tour',
            name='meeting_point_address',
            field=models.CharField(blank=True, help_text='Address or description of the meeting point', max_length=500, verbose_name='Meeting Point Address'),
        ),
        migrations.AddField(
            model_name='tour',
            name='meeting_point_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of the meeting point', max_digits=9, null=True, verbose_name='Meeting Point Latitude'),
        ),
        migrations.AddField(
            model_name='tour',
            name='meeting_point_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of the meeting point', max_digits=9, null=True, verbose_name='Meeting Point Longitude'),
        ),
        migrations.AddField(
            model_name='tour',
            name='start_date',
            field=models.DateField(blank=True, help_text='Date when the tour begins', null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='touractivity',
            name='duration',
            field=models.IntegerField(help_text='Expected duration of the activity in hours', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duration (hours)'),
        ),
    ]
