# Generated by Django 5.2.2 on 2025-07-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_tourbooking_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourbooking',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Amount Paid'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='payment_percentage',
            field=models.IntegerField(choices=[(20, '20% - Acompte'), (50, '50% - Demi-paiement'), (100, '100% - Paiement complet')], default=100, verbose_name='Payment Percentage'),
        ),
    ]
