# Generated by Django 5.2.2 on 2025-07-08 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_alter_tourbooking_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touractivityimage',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='tourimage',
            name='tour',
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['-date_debut', '-heure_depart'], 'verbose_name': 'Tour', 'verbose_name_plural': 'Tours'},
        ),
        migrations.RemoveField(
            model_name='tour',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='max_participants',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='meeting_point_address',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='meeting_point_latitude',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='meeting_point_longitude',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='min_participants',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='price_per_person',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='tour_type',
        ),
        migrations.AddField(
            model_name='tour',
            name='date_debut',
            field=models.DateField(default=datetime.date.today, verbose_name='Date de début'),
        ),
        migrations.AddField(
            model_name='tour',
            name='duree',
            field=models.IntegerField(default=60, verbose_name='Durée (minutes)'),
        ),
        migrations.AddField(
            model_name='tour',
            name='exigence',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Exigence'),
        ),
        migrations.AddField(
            model_name='tour',
            name='heure_depart',
            field=models.TimeField(default=datetime.time(9, 0), verbose_name='Heure de départ'),
        ),
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='tours/images/', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='tour',
            name='nom_balade',
            field=models.CharField(default='Tour sans nom', max_length=255, verbose_name='Nom de la balade'),
        ),
        migrations.AddField(
            model_name='tour',
            name='nombre_participant_max',
            field=models.IntegerField(default=1, verbose_name='Nombre de participants max'),
        ),
        migrations.AddField(
            model_name='tour',
            name='nombre_participant_min',
            field=models.IntegerField(default=1, verbose_name='Nombre de participants min'),
        ),
        migrations.AddField(
            model_name='tour',
            name='point_rencontre_latitude',
            field=models.FloatField(default=0, verbose_name='Latitude du point de rencontre'),
        ),
        migrations.AddField(
            model_name='tour',
            name='point_rencontre_longitude',
            field=models.FloatField(default=0, verbose_name='Longitude du point de rencontre'),
        ),
        migrations.AddField(
            model_name='tour',
            name='prix_par_personne',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix par personne'),
        ),
        migrations.AddField(
            model_name='tour',
            name='type',
            field=models.CharField(default='autre', max_length=100, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='tour',
            table=None,
        ),
        migrations.DeleteModel(
            name='TourActivity',
        ),
        migrations.DeleteModel(
            name='TourActivityImage',
        ),
        migrations.DeleteModel(
            name='TourImage',
        ),
    ]
