# Generated by Django 5.2.2 on 2025-07-06 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_sites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('is_read', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ZoneDangereuse',
            fields=[
                ('id_zonedangereuse', models.AutoField(primary_key=True, serialize=False)),
                ('nom_zone', models.CharField(max_length=200, verbose_name='Nom de la zone')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('type_danger', models.CharField(choices=[('sanitaire', 'Risque sanitaire'), ('naturel', 'Naturel'), ('accident', 'Accident fréquent'), ('criminalite', 'Criminalité'), ('conflit', 'Conflit'), ('autre', 'Autre')], max_length=20, verbose_name='Type de danger')),
                ('description_danger', models.TextField(verbose_name='Description du danger')),
                ('statut', models.CharField(choices=[('SIGNALEE', 'Signalée'), ('VERIFIEE', 'Vérifiée'), ('RESOLUE', 'Résolue'), ('REJETEE', 'Rejetée')], default='SIGNALEE', max_length=10, verbose_name='Statut')),
                ('date_signalement', models.DateTimeField(auto_now_add=True, verbose_name='Date du signalement')),
                ('guide_rapporteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones_dangereuses_rapportees', to=settings.AUTH_USER_MODEL, verbose_name='Guide rapporteur')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zones_dangereuses', to='tourist_sites.touristsite', verbose_name='Site touristique concerné')),
            ],
            options={
                'verbose_name': 'Zone Dangereuse',
                'verbose_name_plural': 'Zones Dangereuses',
                'ordering': ['-date_signalement', 'nom_zone'],
            },
        ),
        migrations.CreateModel(
            name='ZoneDangereuseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='zones_dangereuses/')),
                ('legend', models.CharField(blank=True, max_length=255, verbose_name='Légende')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tourist_sites.zonedangereuse', verbose_name='Zone dangereuse')),
            ],
        ),
        migrations.CreateModel(
            name='ZoneDangereuseVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(help_text='True pour like, False pour dislike', verbose_name='Vote positif')),
                ('date_vote', models.DateTimeField(auto_now_add=True, verbose_name='Date du vote')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_zones_dangereuses', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='tourist_sites.zonedangereuse', verbose_name='Zone dangereuse')),
            ],
            options={
                'verbose_name': 'Vote Zone Dangereuse',
                'verbose_name_plural': 'Votes Zones Dangereuses',
                'ordering': ['-date_vote'],
                'unique_together': {('zone', 'utilisateur')},
            },
        ),
    ]
