# Generated by Django 5.2.2 on 2025-07-06 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_sites', '0002_notification_zonedangereuse_zonedangereuseimage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZoneDangereuseImage',
        ),
    ]
