# Generated by Django 5.2.2 on 2025-07-01 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslocation',
            name='business_location_type',
            field=models.CharField(blank=True, choices=[('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('tour_operator', 'Tour Operator'), ('transport', 'Transport Company'), ('other', 'Other')], max_length=50, null=True, verbose_name='Business Location Type'),
        ),
    ]
