# Generated by Django 5.2.2 on 2025-07-03 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_useractionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesspermission',
            options={'ordering': ['-created_at'], 'verbose_name': "Permission d'établissement", 'verbose_name_plural': "Permissions d'établissements"},
        ),
        migrations.RemoveIndex(
            model_name='businesspermission',
            name='business_bu_busines_a5dfa3_idx',
        ),
        migrations.RemoveIndex(
            model_name='businesspermission',
            name='business_bu_expires_060b3e_idx',
        ),
        migrations.RemoveIndex(
            model_name='businesspermission',
            name='business_bu_is_acti_7ce395_idx',
        ),
        migrations.AlterField(
            model_name='businesspermission',
            name='business_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='business.businesslocation', verbose_name='Établissement'),
        ),
        migrations.AlterField(
            model_name='businesspermission',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expire le'),
        ),
        migrations.AlterField(
            model_name='businesspermission',
            name='granted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Accordé par'),
        ),
        migrations.AlterField(
            model_name='businesspermission',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='businesspermission',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='businesspermission',
            name='permission_type',
            field=models.CharField(choices=[('view_dashboard', 'Accès au dashboard'), ('view_reports', 'Consultation des rapports'), ('view_settings', 'Consultation des paramètres'), ('manage_rooms', 'Gestion des chambres'), ('manage_bookings', 'Gestion des réservations'), ('manage_customers', 'Gestion des clients'), ('manage_housekeeping', 'Gestion du ménage'), ('manage_amenities', 'Gestion des équipements'), ('manage_menu', 'Gestion du menu'), ('manage_orders', 'Gestion des commandes'), ('manage_tables', 'Gestion des tables'), ('manage_reservations', 'Gestion des réservations'), ('manage_inventory', 'Gestion des stocks'), ('manage_vehicles', 'Gestion des véhicules'), ('manage_rentals', 'Gestion des locations'), ('manage_drivers', 'Gestion des chauffeurs'), ('manage_maintenance', 'Gestion de la maintenance'), ('manage_insurance', 'Gestion des assurances'), ('manage_activities', 'Gestion des activités'), ('manage_bookings', 'Gestion des réservations'), ('manage_guides', 'Gestion des guides'), ('manage_itineraries', 'Gestion des itinéraires'), ('manage_customers', 'Gestion des clients')], max_length=50, verbose_name='Type de permission'),
        ),
        migrations.AlterField(
            model_name='businesspermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='permissionrequest',
            name='permission_type',
            field=models.CharField(choices=[('view_dashboard', 'Accès au dashboard'), ('view_reports', 'Consultation des rapports'), ('view_settings', 'Consultation des paramètres'), ('manage_rooms', 'Gestion des chambres'), ('manage_bookings', 'Gestion des réservations'), ('manage_customers', 'Gestion des clients'), ('manage_housekeeping', 'Gestion du ménage'), ('manage_amenities', 'Gestion des équipements'), ('manage_menu', 'Gestion du menu'), ('manage_orders', 'Gestion des commandes'), ('manage_tables', 'Gestion des tables'), ('manage_reservations', 'Gestion des réservations'), ('manage_inventory', 'Gestion des stocks'), ('manage_vehicles', 'Gestion des véhicules'), ('manage_rentals', 'Gestion des locations'), ('manage_drivers', 'Gestion des chauffeurs'), ('manage_maintenance', 'Gestion de la maintenance'), ('manage_insurance', 'Gestion des assurances'), ('manage_activities', 'Gestion des activités'), ('manage_bookings', 'Gestion des réservations'), ('manage_guides', 'Gestion des guides'), ('manage_itineraries', 'Gestion des itinéraires'), ('manage_customers', 'Gestion des clients')], max_length=50, verbose_name='Permission Type'),
        ),
    ]
