# Generated by Django 5.2.2 on 2025-07-08 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_businessfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessFile',
        ),
    ]
