# Generated by Django 5.2.2 on 2025-07-08 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_delete_businessfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLocationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated', verbose_name='Updated At')),
                ('file', models.FileField(upload_to='business_location_documents/', verbose_name='Document')),
                ('title', models.CharField(max_length=255, verbose_name='Document Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('document_type', models.CharField(choices=[('license', 'License'), ('permit', 'Permit'), ('contract', 'Contract'), ('certificate', 'Certificate'), ('insurance', 'Insurance'), ('other', 'Other')], default='other', max_length=50, verbose_name='Document Type')),
                ('business_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='business.businesslocation', verbose_name='Business Location')),
            ],
            options={
                'verbose_name': 'Business Location Document',
                'verbose_name_plural': 'Business Location Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
