# Generated by Django 5.2.2 on 2025-07-05 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tour_departure_time_tour_meeting_point_address_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tourbooking',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='tour_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='tours.tourschedule', verbose_name='Tour Schedule'),
        ),
    ]
