# Generated by Django 5.2.2 on 2025-07-05 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_add_tour_to_tourbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourbooking',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='tours.tour', verbose_name='Tour'),
        ),
    ]
