# Generated by Django 5.2.2 on 2025-07-03 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_businesslocation_business_location_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated', verbose_name='Updated At')),
                ('permission_type', models.CharField(choices=[('manage_rooms', 'Manage Rooms'), ('manage_bookings', 'Manage Bookings'), ('manage_menu', 'Manage Menu'), ('manage_orders', 'Manage Orders'), ('manage_vehicles', 'Manage Vehicles'), ('manage_tours', 'Manage Tours'), ('manage_reviews', 'Manage Reviews'), ('manage_hours', 'Manage Business Hours'), ('manage_amenities', 'Manage Amenities'), ('manage_images', 'Manage Images'), ('view_analytics', 'View Analytics'), ('manage_staff', 'Manage Staff'), ('full_access', 'Full Access')], max_length=50, verbose_name='Permission Type')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave empty for permanent permission', null=True, verbose_name='Expires At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this permission', verbose_name='Notes')),
                ('business_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='business.businesslocation', verbose_name='Business Location')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Granted By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_permissions', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Business Permission',
                'verbose_name_plural': 'Business Permissions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business_location', 'user'], name='business_bu_busines_a5dfa3_idx'), models.Index(fields=['expires_at'], name='business_bu_expires_060b3e_idx'), models.Index(fields=['is_active'], name='business_bu_is_acti_7ce395_idx')],
                'unique_together': {('business_location', 'user', 'permission_type')},
            },
        ),
        migrations.CreateModel(
            name='PermissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated', verbose_name='Updated At')),
                ('permission_type', models.CharField(choices=[('manage_rooms', 'Manage Rooms'), ('manage_bookings', 'Manage Bookings'), ('manage_menu', 'Manage Menu'), ('manage_orders', 'Manage Orders'), ('manage_vehicles', 'Manage Vehicles'), ('manage_tours', 'Manage Tours'), ('manage_reviews', 'Manage Reviews'), ('manage_hours', 'Manage Business Hours'), ('manage_amenities', 'Manage Amenities'), ('manage_images', 'Manage Images'), ('view_analytics', 'View Analytics'), ('manage_staff', 'Manage Staff'), ('full_access', 'Full Access')], max_length=50, verbose_name='Permission Type')),
                ('requested_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Requested Expiration')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Reviewed At')),
                ('review_notes', models.TextField(blank=True, verbose_name='Review Notes')),
                ('business_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to='business.businesslocation', verbose_name='Business Location')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requester')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_permission_requests', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
            ],
            options={
                'verbose_name': 'Permission Request',
                'verbose_name_plural': 'Permission Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business_location', 'requester'], name='business_pe_busines_ec2fb2_idx'), models.Index(fields=['status'], name='business_pe_status_56694e_idx')],
            },
        ),
    ]
