# Generated by Django 5.2.2 on 2025-07-03 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_businesspermission_permissionrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('view', 'Consultation'), ('create', 'Création'), ('edit', 'Modification'), ('delete', 'Suppression'), ('export', 'Export'), ('import', 'Import'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('permission_grant', 'Accord de permission'), ('permission_revoke', 'Révocation de permission'), ('dashboard_access', 'Accès au dashboard')], max_length=20, verbose_name="Type d'action")),
                ('action_description', models.TextField(verbose_name="Description de l'action")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('business_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_actions', to='business.businesslocation', verbose_name='Établissement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'action utilisateur",
                'verbose_name_plural': "Journaux d'actions utilisateurs",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'business_location', 'action_type'], name='business_us_user_id_ea7b2e_idx'), models.Index(fields=['created_at'], name='business_us_created_51c5f0_idx')],
            },
        ),
    ]
