# Generated by Django 5.2.2 on 2025-07-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='driver_daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tarif journalier du chauffeur pour ce véhicule', max_digits=10, verbose_name='Tarif chauffeur par jour (FCFA)'),
        ),
    ]
