# Generated by Django 5.2.2 on 2025-07-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_restaurantorder_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Nombre de plats disponibles à la vente', verbose_name='Stock disponible'),
        ),
    ]
