# Generated by Django 5.2.2 on 2025-06-26 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated', verbose_name='Updated At')),
                ('license_number', models.CharField(blank=True, max_length=100, verbose_name='license number')),
                ('years_of_experience', models.PositiveIntegerField(default=0, verbose_name='years of experience')),
                ('languages_spoken', models.JSONField(default=list, help_text='List of language codes', verbose_name='languages spoken')),
                ('specializations', models.JSONField(default=list, help_text='List of specialization areas', verbose_name='specializations')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='hourly rate')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('verification_document', models.FileField(blank=True, upload_to='guides/verification/', verbose_name='verification document')),
                ('bio', models.TextField(blank=True, verbose_name='biography')),
                ('business_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='business.businesslocation', verbose_name='business location')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guide_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'guide profile',
                'verbose_name_plural': 'guide profiles',
                'db_table': 'guide_profile',
            },
        ),
    ]
