# Generated by Django 5.2.2 on 2025-07-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_sites', '0003_delete_zonedangereuseimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='zonedangereuse',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='zones_dangereuses/', verbose_name='Image (optionnelle)'),
        ),
    ]
