# Generated by Django 5.2.2 on 2025-07-03 22:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_add_user_action_log'),
        ('wallets', '0002_usertransaction_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLocationWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated', verbose_name='Updated At')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Balance')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('currency', models.CharField(default='XAF', help_text='Three-letter currency code (e.g. XAF)', max_length=3, verbose_name='Currency')),
                ('business_location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='business.businesslocation', verbose_name='Business Location')),
            ],
            options={
                'verbose_name': 'Business Location Wallet',
                'verbose_name_plural': 'Business Location Wallets',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
