# Generated by Django 5.2.2 on 2025-06-26 14:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated', verbose_name='Updated At')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Balance')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('currency', models.CharField(default='XAF', help_text='Three-letter currency code (e.g. XAF)', max_length=3, verbose_name='Currency')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='business.business', verbose_name='Business')),
            ],
            options={
                'verbose_name': 'Business Wallet',
                'verbose_name_plural': 'Business Wallets',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated', verbose_name='Updated At')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Balance')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('currency', models.CharField(default='XAF', help_text='Three-letter currency code (e.g. XAF)', max_length=3, verbose_name='Currency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Wallet',
                'verbose_name_plural': 'User Wallets',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated', verbose_name='Updated At')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('PAYMENT', 'Payment'), ('HOLD', 'Hold'), ('REFUND', 'Refund')], max_length=20, verbose_name='Transaction Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Amount')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Status')),
                ('reference', models.CharField(help_text='Unique transaction reference', max_length=100, unique=True, verbose_name='Reference')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_transactions', to='wallets.businesstransaction', verbose_name='Related Transaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallets.businesswallet', verbose_name='Business Wallet')),
            ],
            options={
                'verbose_name': 'Business Transaction',
                'verbose_name_plural': 'Business Transactions',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['reference'], name='wallets_bus_referen_83af56_idx'), models.Index(fields=['status'], name='wallets_bus_status_8ae0b4_idx'), models.Index(fields=['wallet', '-created_at'], name='wallets_bus_wallet__7b55c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated', verbose_name='Updated At')),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('PAYMENT', 'Payment'), ('HOLD', 'Hold'), ('REFUND', 'Refund')], max_length=20, verbose_name='Transaction Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Amount')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Status')),
                ('reference', models.CharField(help_text='Unique transaction reference', max_length=100, unique=True, verbose_name='Reference')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_transactions', to='wallets.usertransaction', verbose_name='Related Transaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='wallets.userwallet', verbose_name='User Wallet')),
            ],
            options={
                'verbose_name': 'User Transaction',
                'verbose_name_plural': 'User Transactions',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['reference'], name='wallets_use_referen_ec354e_idx'), models.Index(fields=['status'], name='wallets_use_status_d83f71_idx'), models.Index(fields=['wallet', '-created_at'], name='wallets_use_wallet__8c570c_idx')],
            },
        ),
    ]
