# Generated by Django 5.2.2 on 2025-07-03 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wallets', '0003_businesslocationwallet'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usertransaction',
            name='wallets_use_wallet__8c570c_idx',
        ),
        migrations.RenameField(
            model_name='usertransaction',
            old_name='object_id',
            new_name='wallet_object_id',
        ),
        migrations.RemoveField(
            model_name='usertransaction',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='usertransaction',
            name='wallet',
        ),
        migrations.AddField(
            model_name='usertransaction',
            name='wallet_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype'),
        ),
    ]
