# Generated by Django 5.2.2 on 2025-07-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0005_usertransaction_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstransaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('PAYMENT', 'Payment'), ('CASH_PAYMENT', 'Cash Payment'), ('HOLD', 'Hold'), ('REFUND', 'Refund')], max_length=20, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER', 'Transfer'), ('PAYMENT', 'Payment'), ('CASH_PAYMENT', 'Cash Payment'), ('HOLD', 'Hold'), ('REFUND', 'Refund')], max_length=20, verbose_name='Transaction Type'),
        ),
    ]
