from django.urls import path
from . import views

app_name = 'vehicles'

urlpatterns = [
    # Vehicle Categories
    path('categories/',
         views.VehicleCategoryListView.as_view(),
         name='category_list'),
    path('categories/create/',
         views.VehicleCategoryCreateView.as_view(),
         name='category_create'),
    path('categories/<int:pk>/update/',
         views.VehicleCategoryUpdateView.as_view(),
         name='category_update'),

    # Vehicles
    path('',
         views.VehicleListView.as_view(),
         name='vehicle_list'),
    path('search/',
         views.vehicle_search_view,
         name='vehicle_search'),
    path('<int:pk>/',
         views.VehicleDetailView.as_view(),
         name='vehicle_detail'),
    path('create/',
         views.VehicleCreateView.as_view(),
         name='vehicle_create'),
    path('<int:pk>/update/',
         views.VehicleUpdateView.as_view(),
         name='vehicle_update'),
    path('<int:vehicle_pk>/images/add/',
         views.VehicleImageCreateView.as_view(),
         name='vehicle_image_create'),

    # Drivers
    path('drivers/',
         views.DriverListView.as_view(),
         name='driver_list'),
    path('drivers/<int:pk>/',
         views.DriverDetailView.as_view(),
         name='driver_detail'),
    path('drivers/create/',
         views.DriverCreateView.as_view(),
         name='driver_create'),
    path('drivers/<int:pk>/update/',
         views.DriverUpdateView.as_view(),
         name='driver_update'),

    # Bookings
    path('bookings/',
         views.VehicleBookingListView.as_view(),
         name='booking_list'),
    path('rentals/',
         views.VehicleRentalListView.as_view(),
         name='rental_list'),
    path('bookings/<int:pk>/',
         views.VehicleBookingDetailView.as_view(),
         name='booking_detail'),
    path('bookings/create/<int:vehicle_id>/',
         views.vehicle_booking_create,
         name='booking_create'),
    path('bookings/<int:pk>/update/',
         views.VehicleBookingUpdateView.as_view(),
         name='booking_update'),
    path('bookings/<int:pk>/payment/',
         views.vehicle_booking_payment_view,
         name='booking_payment'),
    path('bookings/<int:pk>/finalize-payment/',
         views.finalize_payment_admin,
         name='finalize_payment_admin'),
    path('bookings/<int:pk>/process-cash-payment/',
         views.process_cash_payment,
         name='process_cash_payment'),
    path('bookings/<int:pk>/approve/',
         views.approve_booking,
         name='approve_booking'),
] 