# Generated by Django 5.2.2 on 2025-06-26 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated', verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('max_occupancy', models.PositiveIntegerField(verbose_name='Maximum occupancy')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price per night', max_digits=10, verbose_name='Base price')),
                ('amenities', models.JSONField(blank=True, help_text='List of amenities included with this room type', null=True, verbose_name='Amenities')),
                ('image', models.ImageField(blank=True, upload_to='rooms/room_types/', verbose_name='Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Room type',
                'verbose_name_plural': 'Room types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated', verbose_name='Updated At')),
                ('room_number', models.CharField(max_length=50, verbose_name='Room number')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Floor')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per night')),
                ('max_occupancy', models.PositiveIntegerField(verbose_name='Maximum occupancy')),
                ('amenities', models.JSONField(blank=True, help_text='Room-specific amenities', null=True, verbose_name='Amenities')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is available')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Maintenance mode')),
                ('business_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='business.businesslocation', verbose_name='Business location')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='rooms.roomtype', verbose_name='Room type')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['room_number'],
                'unique_together': {('business_location', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated', verbose_name='Updated At')),
                ('image', models.ImageField(upload_to='rooms/galleries/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Caption')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.room', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Room image',
                'verbose_name_plural': 'Room images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when this record was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time when this record was last updated', verbose_name='Updated At')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Commission Amount')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed'), ('NO_SHOW', 'No Show')], default='PENDING', max_length=20, verbose_name='Status')),
                ('booking_reference', models.CharField(max_length=50, unique=True, verbose_name='Booking Reference')),
                ('special_requests', models.TextField(blank=True, null=True, verbose_name='Special Requests')),
                ('customer_notes', models.TextField(blank=True, null=True, verbose_name='Customer Notes')),
                ('cancellation_reason', models.TextField(blank=True, null=True, verbose_name='Cancellation Reason')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelled At')),
                ('check_in_date', models.DateField(verbose_name='Check-in Date')),
                ('check_out_date', models.DateField(verbose_name='Check-out Date')),
                ('adults_count', models.PositiveIntegerField(default=1, verbose_name='Number of Adults')),
                ('children_count', models.PositiveIntegerField(default=0, verbose_name='Number of Children')),
                ('hotel_notes', models.TextField(blank=True, null=True, verbose_name='Hotel Notes')),
                ('business_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_bookings', to='business.businesslocation', verbose_name='Business Location')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='rooms.room', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Room Booking',
                'verbose_name_plural': 'Room Bookings',
                'ordering': ['-created_at'],
                'unique_together': {('room', 'check_in_date')},
            },
        ),
    ]
