# .github/workflows/hello.yml
name: Hello World CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  hello:
    runs-on: ubuntu-latest
    
    steps:
      - name: Dire bonjour
        run: echo "👋 Hello World !"
      
      - name: Afficher la date
        run: date
      
      - name: Afficher les variables d'environnement
        run: env